version: 0.2

env:
  parameter-store:
   DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
   DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
   DOCKER_REGISTRY_URL: /myapp/docker-credentials/url
 
phases:
  install:
    runtime-versions:
        python: 3.11
    
  pre_build:
    commands:
     - echo "installing the requirements mentioned in the file here we have only on that is flask"
     - pip install -r myfirst-python-project/requirements.txt
  build:
    commands:
       - echo "creating image "
       - cd myfirst-python-project/
       - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
       - docker build -t "docker.io/ashirwad505/myfirst-python-project:latest" .
       - docker image ls
       - docker push "docker.io/ashirwad505/myfirst-python-project:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"     
artifacts:
  files:
    - '**/*'
  base-directory: ../myfirst-python-project
